### ISSUE TITLE
Error claiming PVC byte measurement

### ISSUE THREAD

**Issue by haije** [nmaupu/freenas-provisioner#21]
I've setup the deployment following the guide. Everything runs well and is deployed correctly. When I try create a PVC the status says pending and the freenas pod state the following in the logs:

```$ kubectl -n kube-system logs -f freenas-nfs-provisioner-597d5b54ff-lcjkn
[...]

I0208 11:24:44.552136       1 controller.go:926] provision "default/test" class "freenas-nfs": started
I0208 11:24:44.554605       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test", UID:"a53f182d-2b93-11e9-b69e-005056a6835c", APIVersion:"v1", ResourceVersion:"2742491", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test"
E0208 11:24:44.557407       1 controller.go:688] Giving up syncing claim "default/test" because failures 15 >= threshold 15
E0208 11:24:44.557427       1 controller.go:700] error syncing claim "default/test": failed to provision volume with StorageClass "freenas-nfs": byte quantity must be a positive integer with a unit of measurement like M, MB, MiB, G, GiB, or GB
I0208 11:24:44.557629       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test", UID:"a53f182d-2b93-11e9-b69e-005056a6835c", APIVersion:"v1", ResourceVersion:"2742491", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "freenas-nfs": byte quantity must be a positive integer with a unit of measurement like M, MB, MiB, G, GiB, or GB
```

I cannot find the message in the code nor anywhere else in Kubernetes. I am not sure if it is a message from FreeNAS or from Kubernetes.

I am using FreeNAS 11.2 and kubernetes 1.11. Any thoughts about this issue? Or people who have the same issues?

**Comment by nmaupu** [comment]
Hi,

Can you provide your claim ?

**Comment by haije** [comment]
Hi,

This is my class.yaml

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: freenas-nfs
#  annotations:
#    storageclass.kubernetes.io/is-default-class: "true"
provisioner: freenas.org/nfs
allowVolumeExpansion: true
reclaimPolicy: Delete
mountOptions: []
parameters:
  # namespace of the secret which contains FreeNAS server connection details
  # default: kube-system
  serverSecretNamespace: "kube-system"

  # name of the secret which contains FreeNAS server connection details
  # default: freenas-nfs
  serverSecretName: "freenas-nfs"

  # the name of the parent dataset (or simply pool) where all resources will
  # be created, it *must* exist before provisioner will work
  # example: tank/k8s/mycluster
  # default: tank
  datasetParentName: "Data/Kubernetes"

  # whether to enforce quotas for each dataset
  # if enabled each newly provisioned dataset will set the appropriate quota
  # per the PVC
  # default: true
  datasetEnableQuotas: "true"

  # whether to reserve space when the dataset is create
  # if enabled each newly provisioned dataset will set the appropriate value
  # per the PVC
  # default: true
  datasetEnableReservation: "false"

  # if enabled provisioner will create parent datasets for each namespace
  # otherwise, all datasets will be provisioned in a flat manner
  # default: true
  datasetEnableNamespaces: "true"

  # if datasetEnableNamespaces is enabled, sets a per-namespace quota
  # example: 5M | 10G | 1T  (M, Mi, MB, MiB, G, Gi, GB, GiB, T, Ti, TB, or TiB)
  # default: 0 (no quota)
  datasetNamespaceQuota: "0"

  # if datasetEnableNamespaces is enabled, sets a per-namespace reservation
  # this should not be greater than the datasetNamespaceQuota
  # example: 5M | 10G | 1T  (M, Mi, MB, MiB, G, Gi, GB, GiB, T, Ti, TB, or TiB)
  # default: 0
  datasetNamespaceReservation: "0"

  # if enabled created datasets will adhere to reliable pattern
  # if datasetNamespaces == true dataset pattern is: <datasetParentName>/<namespace>/<PVC Name>
  # if datasetNamespaces == false dataset pattern is: <datasetParentName>/<namespace>-<PVC Name>
  # if disabled, datasets will be created with a name pvc-<uid> (the name of the provisioned PV)
  # default: true
  datasetDeterministicNames: "true"

  # if enabled and datasetDeterministicNames is enabled then dataset that
  # already exist (pre-povisioned out of band) will be ratained by the
  # provisioner during deletion of the reclaim process
  # ignored if datasetDeterministicNames is disabled (collisions result in failure)
  # default: true
  datasetRetainPreExisting: "true"

  # the following parameters determine permissions and ownership of the
  # dataset mount directory (on FreeNAS) immediately upon creation
  # default: 0777, root, wheel
  datasetPermissionsMode: "0777"
  datasetPermissionsUser: "root"
  datasetPermissionsGroup: "wheel"

  # this determines what the 'server' property of the NFS share will be in
  # in kubernetes, it's purpose is to provide flexibility between the control
  # and data planes of FreeNAS
  # default: uses the 'host' value from the secret
  #shareHost:

  # determines if newly created NFS shares will have the 'All Directories'
  # option checked
  # default: true
  shareAlldirs: "true"

  # Authorized hosts/networks (space-separated) allowed to access the shares
  # default: ""
  #shareAllowedHosts:
  shareAllowedNetworks: "10.0.0.0/24, 192.168.0.0/24"

  # Determines root mapping
  # cannot be used simultaneously with shareMapAll{User,Group}
  # default: root:wheel
  shareMaprootUser: "root"
  shareMaprootGroup: "wheel"

  # Determines user mapping for all access (not recommended)
  # cannot be used simultaneously with shareMaproot{User,Group}
  # default: ""
  #shareMapallUser:
  #shareMapallGroup:

  # if enabled and datasetDeterministicNames is enabled then shares that
  # already exist (pre-provisioned out of band) will be retained by the
  # provisioner during deletion of the reclaim process
  # ignored if datasetDeterministicNames is disabled (collisions result in failure)
  # default: true
  shareRetainPreExisting: "true"
```

And this is my claim.yaml

```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test
spec:
  storageClassName: freenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "100Gi"
```

No matter if I try 100G 100GB, 100M, 100Mi, nothing works. Am I doing something wrong?
