### ISSUE TITLE
claiming storage fails with "invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by intrand** [nmaupu/freenas-provisioner#31]
Here's the log from the freenas-provisioner container:
```
W1123 16:48:09.350090       1 controller.go:685] Retrying syncing claim "default/freenas-test-pvc" because failures 0 < threshold 15
E1123 16:48:09.350480       1 controller.go:700] error syncing claim "default/freenas-test-pvc": failed to provision volume with StorageClass "freenas-nfs": invalid character '<' looking for beginning of value
```

After reading through the code, I'm *guessing* it's getting HTML back and, obviously, can't parse it correctly.

`curl`ing the same FreeNAS API endpoint directly from within the cluster works perfectly fine, and I've verified you're looking for the right fields with the right data types in the response.

I really wish there was a debug/loglevel flag I could pass to see the raw responses from FreeNAS to aid in troubleshooting.

I've tried versions 2.3, 2.4 and 2.5 from docker hub.

Here's the spam of my uninteresting YAML:
```YAML
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: freenas-nfs-provisioner
  namespace: kube-system
  labels:
    app: freenas-nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freenas-nfs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: freenas-nfs-provisioner
    spec:
      serviceAccountName: freenas-nfs-provisioner
      containers:
        - name: freenas-nfs-provisioner
          image: docker.io/nmaupu/freenas-provisioner:2.3

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: freenas-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: freenas.org/nfs
allowVolumeExpansion: true
reclaimPolicy: Delete
mountOptions: []
parameters:
  datasetParentName: "data/kube"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: freenas-test-pvc
spec:
  storageClassName: freenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10M


```

Secret was entirely omitted, but I can tell you that I'm using HTTPS to an IP with port 443 with allowInsecure turned on. Unlike the other yaml resource files above, **I've supplied answers to every key in the sample secret.yaml.** All values are base64.

If I can help any more, please let me know.

Thanks!
