### ISSUE TITLE
Broken in FreeNAS 11.3-RELEASE 

### ISSUE THREAD

**Issue by maxirus** [nmaupu/freenas-provisioner#34]
Seems FreeNAS `v11.3-RELEASE` changed the capacity to IEC Suffixes. New PVC yield the error:

```
I0212 04:58:09.995962       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"test", Name:"test-config", UID:"9f22bf96-256f-405f-adc4-9f6bb5ca373f", APIVersion:"v1", ResourceVersion:"1431038", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "freenas-nfs": Error creating dataset "tank/Kubernetes/test/test-config" - message: {"refquota":["Specify the value with IEC suffixes, e.g. 10 GiB"]}, status: 400
```

This happens when setting `spec.resources.requests.storage` to `nG` and `nGi`.

Does [this](https://github.com/nmaupu/freenas-provisioner/blob/af839b6cdf49b6c01101780be25185c15cd42985/provisioner/provisioner.go#L287) need to suffix the value with `B`?

**Comment by travisghansen** [comment]
Hmm, that's odd. We actually send that value as an integer I believe so it converts whatever the value is in the request to a number. I'll have to do an 11.3 install and see what's up.

**Comment by maxirus** [comment]
I have been searching the FreeNAS code base looking for this message and all I've come up with thus far is an old version of it [here](https://webcache.googleusercontent.com/search?q=cache:i5pIHhUCy4EJ:https://github.com/freenas/freenas/blob/master/gui/freeadmin/forms.py+&cd=8&hl=en&ct=clnk&gl=us&client=safari#L323).

My guess is the RegEx changed.

**Comment by travisghansen** [comment]
I'll update my test system to 11.3 and do some trial and error and see what I can find. It's really unfortunate they keep making changes like this making it difficult to maintain sanity across versions :(

In the csi driver all the zfs operations are done via the cli over ssh so this kind of garbage should be highly mitigated.

**Comment by maxirus** [comment]
Sounds good. Let me know if I can help in anyway. In the mean time I will keep trying to debug.

One thing to note, it does appear this code base simply passes along the value in `spec.resources.requests.storage` in the PVC. In K8s that's `10GiB` for example. In the FreeNAS UI, this option is formatted to `10 GiB` (notice the space). Not sure if this makes a difference.

Also, I noticed none of the PVC I created **before** upgrading to 11.3 have their quotas set even though I have it enabled. I'm wondering if in `v11.2` if this simply silently failed.

**Comment by travisghansen** [comment]
What version of `11.2` have you been running. I've been on various versions of `11.2` for a long time and the quotas are always set.

I'm wondering if this is connected to creating the namespace dataset...do you have that enabled? Subsequently, do you have quotas enabled on the namespaces?

Can you send over a copy of your `class` definition?

**Comment by travisghansen** [comment]
Yeah, so I've confirmed the provisioner does send the value as an integer/number in the JSON over the wire. Also confirmed that `11.3` is rejecting that syntax which is highly unfortunate. To make matters worse the response value for that field is still returned as a number in the json.

My `go` skills are pretty limited but the structs that marshal/unmarshal this stuff expect the value types to be the same for both in/outbound so I'm not sure if it's even possible to deal with this without a major headache. Perhaps @nmaupu has some idea?

It does appear as if `11.2` supports sending the value as a string so at least there's that (meaning, if we change it to send a string we hopefully aren't breaking all the older versions for FreeNAS). Not sure if all the older versions of FreeNAS would support that syntax though..

**Comment by travisghansen** [comment]
Pretty sure this diff would solve your problem:

```
diff --git a/freenas/dataset.go b/freenas/dataset.go
index 0305c74..f7d25ea 100644
--- a/freenas/dataset.go
+++ b/freenas/dataset.go
@@ -6,6 +6,7 @@ import (
        "fmt"
        "github.com/golang/glog"
        "path/filepath"
+       "strconv"
 )
 
 var (
@@ -27,6 +28,41 @@ type Dataset struct {
        Comments       string `json:"comments,omitempty"`
 }
 
+func (d *Dataset) MarshalJSON() ([]byte, error) {
+       data := &struct {
+               Avail          int64  `json:"avail,omitempty"`
+               Mountpoint     string `json:"mountpoint,omitempty"`
+               Name           string `json:"name"`
+               Pool           string `json:"pool"`
+               Recordsize     int64  `json:"recordsize,omitempty"`
+               Quota          int64  `json:"quota,omitempty"`
+               Reservation    int64  `json:"reservation,omitempty"`
+               Refquota       string `json:"refquota,omitempty"`
+               Refreservation int64  `json:"refreservation,omitempty"`
+               Refer          int64  `json:"refer,omitempty"`
+               Used           int64  `json:"used,omitempty"`
+               Comments       string `json:"comments,omitempty"`
+       }{
+               Avail:          d.Avail,
+               Mountpoint:     d.Mountpoint,
+               Name:           d.Name,
+               Pool:           d.Pool,
+               Recordsize:     d.Recordsize,
+               Quota:          d.Quota,
+               Reservation:    d.Reservation,
+               Refreservation: d.Refreservation,
+               Refer:          d.Refer,
+               Used:           d.Used,
+               Comments:       d.Comments,
+       }
+
+       if d.Refquota > 0 {
+               data.Refquota = strconv.FormatInt(d.Refquota, 10) + "b"
+       }
+
+       return json.Marshal(data)
+}
+
 func (d *Dataset) String() string {
        return filepath.Join(d.Pool, d.Name)
 }
```

Based on suggestions here: http://choly.ca/post/go-json-marshalling/

**Comment by maxirus** [comment]
> What version of 11.2 have you been running.

I was on `v11.2-U7`.

> I'm wondering if this is connected to creating the namespace dataset...do you have that enabled? 

Yes

> Subsequently, do you have quotas enabled on the namespaces?

No

> Can you send over a copy of your class definition?

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: freenas-nfs
  labels:
    app.kubernetes.io/instance: mighty-mosquito
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: freenas-provisioner
    app.kubernetes.io/version: '2.5'
    helm.sh/chart: freenas-provisioner-0.1.1
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: freenas.org/nfs
parameters:
  datasetDeterministicNames: 'true'
  datasetEnableNamespaces: 'true'
  datasetEnableQuotas: 'true'
  datasetEnableReservation: 'false'
  datasetParentName: tank/Kubernetes
  datasetPermissionsGroup: wheel
  datasetPermissionsMode: '0777'
  datasetPermissionsUser: root
  datasetRetainPreExisting: 'true'
  serverSecretName: freenas-nfs
  serverSecretNamespace: freenas
  shareAlldirs: 'true'
  shareAllowedHosts: ''
  shareAllowedNetworks: ''
  shareMaprootGroup: wheel
  shareMaprootUser: root
  shareRetainPreExisting: 'true'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

So you're saying `options.PVC.Spec.Resources.Requests[v1.ResourceName(v1.ResourceStorage)].Value()` returns an integer? Is it converting the String (ie. `10 GiB`) to bytes as an Integer? Interesting that the [API Docs](http://api.freenas.org/resources/storage.html#id2) show an integer in the example yet the Docs say the data type is expecting a string.
